---
- hosts: database
  gather_facts: true
  roles:
    - jfrog/ansible/roles/postgres

- hosts: primary
  gather_facts: true
  roles:
    - jfrog/ansible/roles/artifactory
    - jfrog/ansible/roles/artifactory-nginx-ssl
