apiVersion: apps/v1
kind: Deployment
metadata:
  name: artifactory-ha-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: artifactory-ha-operator
  template:
    metadata:
      labels:
        name: artifactory-ha-operator
    spec:
      serviceAccountName: artifactory-ha-operator
      containers:
        - name: artifactory-ha-operator
          image: image-registry.openshift-image-registry.svc:5000/jfrog-artifactory/artifactory-ha
          imagePullPolicy: IfNotPresent
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "artifactory-ha-operator"
