apiVersion: apps/v1
kind: Deployment
metadata:
  name: artifactory-ha-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: artifactory-ha-operator
  template:
    metadata:
      labels:
        name: artifactory-ha-operator
    spec:
      serviceAccountName: artifactory-ha-operator
      containers:
        - name: artifactory-ha-operator
          image: quay.io/jfrog/artifactory-ha-operator
          imagePullPolicy: IfNotPresent
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "artifactory-ha-operator"
            - name: RELATED_IMAGE_ARTIFACTORY_IMAGE_REPOSITORY
              value: "quay.io/jfrog/artifactory-rh-pro"
            - name: RELATED_IMAGE_NGINX_IMAGE_REPOSITORY
              value: "quay.io/jfrog/nginx-artifactory-rh-pro"
            - name: DATABASE_TYPE
              value: "OVERRIDE"
            - name: DATABASE_DRIVER
              value: "OVERRIDE"
            - name: DATABASE_URL
              value: "OVERRIDE"
            - name: DATABASE_USER
              value: "OVERRIDE"
            - name: DATABASE_PASSWORD
              value: "OVERRIDE"