kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv0003-large
spec:
  capacity:
    storage: 200Gi
  hostPath:
    path: /mnt/pv-data/pv0003-large
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Recycle
  volumeMode: Filesystem
