# Openshift artifactory ha
# Requires one custom init container
# to resolve the user id perm issue with redhat
artifactory-ha:
  artifactory:
    ## Add custom init containers execution before predefined init containers
    customInitContainersBegin: |
      - name: "redhat-custom-setup"
        image: "{{ .Values.initContainerImage }}"
        imagePullPolicy: "{{ .Values.artifactory.image.pullPolicy }}"
        command:
          - 'sh'
          - '-c'
          - 'chown -R 1030:1030 {{ .Values.artifactory.persistence.mountPath }}'
        securityContext:
            runAsUser: 0
        volumeMounts:
          - mountPath: "{{ .Values.artifactory.persistence.mountPath }}"
            name: volume
    ## Add custom init containers
