# permissions for end users to view openshiftartifactoryhas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openshiftartifactoryha-viewer-role
rules:
- apiGroups:
  - cache.jfrog.com
  resources:
  - openshiftartifactoryhas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.jfrog.com
  resources:
  - openshiftartifactoryhas/status
  verbs:
  - get
