apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.0.1
    operators.operatorframework.io/project_layout: helm.sdk.operatorframework.io/v1
  name: pipeline-operator.vX.Y.Z
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: Pipeline Enterprise Operator
  displayName: Pipeline Enterprise Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - DevOps
  - Integrations
  - Application Delivery
  links:
  - name: Pipeline Operator
    url: https://pipeline-operator.domain
  maintainers:
  - email: johnp@jfrog.com
    name: johnp
  - email: vinaya@jfrog.com
    name: vinay
  maturity: alpha
  provider:
    name: JFrog Ltd
  version: 0.0.0
