# Openshift Jfrog Xray
xray:
  unifiedUpgradeAllowed: true
  replicaCount: 1
  xray:
    masterKey: FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    joinKey: EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
    consoleLog: false
    jfrogUrl: "OVERRIDE"
  postgresql:
    enabled: false
  database:
    url: "OVERRIDE"
    user: "OVERRIDE"
    password: "OVERRIDE"
  rabbitmq-ha:
    enabled: true
    replicaCount: 1
    image:
      tag: 3.7.21-alpine
    rabbitmqUsername: guest
    rabbitmqPassword: ""
    persistentVolume:
      enabled: true
      size: 20Gi
    rbac:
      create: true
    preStartCommand:
  global:
    postgresqlTlsSecret:
  analysis:
    name: xray-analysis
    image:
      repository: registry.connect.redhat.com/jfrog/xray-analysis
      version: 3.3.0
    updateStrategy: RollingUpdate
    podManagementPolicy: Parallel
    preStartCommand:
  indexer:
    name: xray-indexer
    image:
      repository: registry.connect.redhat.com/jfrog/xray-indexer
      version: 3.3.0
    updateStrategy: RollingUpdate
    podManagementPolicy: Parallel
  persist:
    name: xray-persist
    image:
      repository: registry.connect.redhat.com/jfrog/xray-persist
      version: 3.3.0
    updateStrategy: RollingUpdate
    podManagementPolicy: Parallel
    persistence:
      size: 10Gi
    preStartCommand:
  server:
    name: xray-server
    image:
      repository: registry.connect.redhat.com/jfrog/xray-server
      version: 3.3.0
    updateStrategy: RollingUpdate
    podManagementPolicy: Parallel
    replicaCount: 1
  router:
    name: router
    image:
      repository: registry.connect.redhat.com/jfrog/xray-router
      version: 1.2.1
      imagePullPolicy: IfNotPresent
  rabbitmq-ha:
    enabled: true
    replicaCount: 1
    image:
      repository: registry.connect.redhat.com/jfrog/xray-rabbitmq
      tag: 3.8.0
    rabbitmqEpmdPort: 4369
    rabbitmqNodePort: 5672
    rabbitmqManagerPort: 15672