# Openshift Jfrog Xray
xray:
  replicaCount: 1
  xray:
    masterKey: FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    joinKey: EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
    consoleLog: false
    jfrogUrl: "OVERRIDE"
  postgresql:
    enabled: false
  database:
    url: "OVERRIDE"
    user: "OVERRIDE"
    password: "OVERRIDE"
  rabbitmq-ha:
    enabled: true
    replicaCount: 1
    image:
      tag: 3.7.21-alpine
    rabbitmqUsername: guest
    rabbitmqPassword: ""
    persistentVolume:
      enabled: true
      size: 20Gi
    rbac:
      create: true
    preStartCommand:
  global:
    postgresqlTlsSecret:
  analysis:
    name: xray-analysis
    image:
      repository: quay.io/jfrog/xray-analysis-rh
      # version:
    updateStrategy: RollingUpdate
    podManagementPolicy: Parallel
    preStartCommand:
  indexer:
    name: xray-indexer
    image:
      repository: quay.io/jfrog/xray-indexer-rh
      # version:
    updateStrategy: RollingUpdate
    podManagementPolicy: Parallel
  persist:
    name: xray-persist
    image:
      repository: quay.io/jfrog/xray-persist-rh
      # version:
    updateStrategy: RollingUpdate
    podManagementPolicy: Parallel
    persistence:
      size: 10Gi
    preStartCommand:
  server:
    name: xray-server
    image:
      repository: quay.io/jfrog/xray-server-rh
      # version:
    updateStrategy: RollingUpdate
    podManagementPolicy: Parallel
    replicaCount: 1
  router:
    name: router
    image:
      repository: quay.io/jfrog/router-rh
      version: 1.2.1
      imagePullPolicy: IfNotPresent
  rabbitmq-ha:
    enabled: true
    replicaCount: 1
    image:
      repository: quay.io/jfrog/xray-rabbitmq-rh
      tag: 3.8.0
    rabbitmqEpmdPort: 4369
    rabbitmqNodePort: 5672
    rabbitmqManagerPort: 15672