apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: openshiftpipelines.charts.helm.k8s.io
spec:
  group: charts.helm.k8s.io
  names:
    kind: OpenshiftPipeline
    listKind: OpenshiftPipelineList
    plural: openshiftpipelines
    singular: openshiftpipeline
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ''
    plural: ''
  conditions: null
  storedVersions: null
